### ISSUE TITLE
为什么RootActivity的onkeydown 不能继承

### ISSUE THREAD

**Issue by Aarthas** [Mr-wangyong/FragmentStack#2]
我的需求是，当用户按下返回键，不退出activity

  @Override
    public boolean onKeyDown(int keyCode, KeyEvent event)
    {
        switch (keyCode)
        {
            case KeyEvent.KEYCODE_BACK:
                return true;
        }
        return super.onKeyDown(keyCode, event);
    }

**Comment by Mr-wangyong** [comment]
你好，因为框架本身需要用到返回键事件，所以做了拦截操作，当然，也考虑到了扩展，提供了相关接口进行服务，你可以直接在任何继承了RootActivity中使用setKeyCallBack（new KeyCallBack）来进行相关的操作，如果有任何问题，欢迎及时issues,非常感谢您的关注！！
