### ISSUE TITLE
gradel error

### ISSUE THREAD

**Issue by antoniomerlin** [Mr-wangyong/FragmentStack#3]
Failed to resolve com.mrwang.Fragmenttack:stacklibrary:1.0.0

**Comment by wxmylife** [comment]
Error:(54, 13) Failed to resolve: com.mrwang.Fragmenttack:stacklibrary:1.0.0
Show in File 
Show in Project Structure dialog

**Comment by changkai244** [comment]
compile 'com.github.Mr-wangyong:FragmentStack:v1.0.0' 这个才是他的compile

**Comment by Mr-wangyong** [comment]
compile 'com.github.Mr-wangyong:FragmentStack:v1.0.2'  is already success
