### ISSUE TITLE
跳轉多次fragment后，按back返回不到主頁面（fragment無限loop）

### ISSUE THREAD

**Issue by jiulian** [Mr-wangyong/FragmentStack#4]
幾次亂按fragment button會添加非常多的fragment到stack裡面，一直按返回卻又回不到主頁。甚至有空白頁、重疊的頁面出現。

**Comment by Mr-wangyong** [comment]
由於Fragment創建速度非常快,所有,建議增加click事件攔截,例如5秒鐘之內點擊無效,此框架也支持此功能,謝謝您的支持!!

**Comment by bennyhuo** [comment]
这个问题是因为你没有对 Fragment 的切换操作进行队列处理，另外框架里面的 500ms 的处理是有问题的，上层调用了你的接口，你没有响应也没有反馈，这样外部的代码很容易出现不一致。

实际上如果你不给fragment添加切换动画就没有那么容易触发这类问题，出现这些问题的原因主要是fragment的转场动画播放的时间间隙，这段时间内是不能进行其他涉及到该fragment的操作的，作为一个单Activity的框架，这时候其他fragment从设计上来讲也不应该有操作。

**Comment by fqclovelal** [comment]
问题解决了吗？我也遇到了这个问题
