### ISSUE TITLE
how to customize the system back button inside fragment

### ISSUE THREAD

**Issue by antoniomerlin** [Mr-wangyong/FragmentStack#5]
Hey, its a nice library thnks for it.
Can you please provide me example for how i can listen for system back button inside a fragment.

**Comment by mr-chengwangyong** [comment]
Hello, thank you for your attention, because you need to listen to the return key to recover the page, so provides an interface keyBack, you can use it
SetKeyCallBack (KeyCallBack new) {
@Override
Boolean onKeyDown public (keyCode int, event KeyEvent) {
False return;
}
});

**Comment by antoniomerlin** [comment]
Actually i want display a dialog over fragment when user press system back button
